project:
  type: book

book:
  title: "R4DS Notes from DJ"
  author: "Jia Ding"
  date: "2025/11/22"
  search: true
  repo-url: https://github.com/SunPast/r4ds
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/ch1_data_visualization.qmd
    - chapters/ch2_workflow_basics.qmd
    - chapters/ch3_data_transformation.qmd
    - chapters/ch4_workflow_code_style.qmd
    - chapters/ch5_data_tidying.qmd
    - chapters/ch6_workflow_scripts_projects.qmd
    - chapters/ch7_data_import.qmd
    - chapters/ch8_workflow_getting_help.qmd
    - chapters/ch9_layers.qmd
    - chapters/ch10_exploratory_data_analysis.qmd
    - chapters/ch11_communication.qmd
    - chapters/ch12_logical_vectors.qmd
    - chapters/ch13_numbers.qmd
    - chapters/ch14_strings.qmd
    - chapters/ch15_regular_expressions.qmd
    - chapters/ch16_factors.qmd
    - chapters/ch17_dates_and_times.qmd
    - chapters/ch18_missing_values.qmd
    - chapters/ch19_joins.qmd
    - chapters/ch20_spreadsheets.qmd
    - chapters/ch21_databases.qmd
    - chapters/ch22_arrow.qmd
    - chapters/ch23_hierarchical_data.qmd
    - chapters/ch24_web_scraping.qmd
    - chapters/ch25_functions.qmd
    - chapters/ch26_iteration.qmd
    - chapters/ch27_field_guide_base_R.qmd
    - chapters/ch28_quarto.qmd
    - chapters/ch29_quarto_formats.qmd
    - afterword.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 2

comments:
  hypothesis: true

editor: visual

